name: tp1_flutter
description: "A new Flutter project."
publish_to: 'none' # Utilisation recommandée pour les projets privés

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  intl: ^0.17.0



flutter:
  uses-material-design: true
  # Exemple d'ajout d'assets (décommentez et ajustez selon vos besoins)
  assets:
     - images/logo.jpg
     - images/clouds.png
     - images/clear.png
     - images/rain.png
  #   - images/a_dot_ham.jpeg

  # Exemple d'ajout de polices personnalisées (décommentez et ajustez selon vos besoins)
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
